### ISSUE TITLE
Check if `rsync` is installed or not

### ISSUE THREAD

**Issue by surajnarwade** [openshift/odo-init-image#22]
`assemble-and-restart` scripts uses `rsync`, but before that it should whether `rsync` is installed or not 

Reference: https://github.com/openshift/odo/issues/1874#issuecomment-506719433

**Comment by cdrage** [comment]
See issue: https://github.com/openshift/odo/issues/1609

This has been fixed upstream: https://github.com/sclorg/httpd-container/issues/78

and implemented here: https://github.com/sclorg/s2i-base-container/pull/169

**Comment by surajnarwade** [comment]
@cdrage , how we can fetch this changes or test changes against new fixes ?

**Comment by cdrage** [comment]
We should implement this at least to error / use alternative methods if `rsync` isn't installed. For example.. if there is no `rsync` copy it over a more "manual" way?
