### ISSUE TITLE
Use go mod for vendor management

### ISSUE THREAD

**Issue by adambkaplan** [openshift/odo-init-image#30]
Vendored third-party code needs to be maintained by a declarative dependency management system. This ensures that if there is a security issue in vendored package, it is easy to identify if our code is vulnerable

`go mod` is the tool of choice - it has been adopted by the Go and Kubernetes communities.
https://blog.golang.org/using-go-modules

**Comment by kadel** [comment]
The vendor directory in this repo is not a Go vendor.

We need third-party programs like [SupervisordD](https://github.com/ochinchina/supervisord) and [dumb-init](https://github.com/Yelp/dumb-init). vendor directory in this repository is used to hold source code for those projects.
