### ISSUE TITLE
support multi arch build of odo-init-image

### ISSUE THREAD

**Issue by jichenjc** [openshift/odo-init-image#49]
https://access.redhat.com/containers/?tab=overview#/registry.access.redhat.com/openshiftdo/odo-init-image-rhel7
mentioned it's only support x86 but not other arch

do we have any plan before that this will be supported for IBM z arch or power arch?
as you can see odo which is highly relied by other dev tools rely on odo-init-image to init

**Comment by kadel** [comment]
The plan is actually moving away from using odo-init-image.
Everything that we are building around Devfiles (https://github.com/openshift/odo/labels/area%2Fdevfile) is not going to require odo-init-image anymore.

**Comment by jichenjc** [comment]
@kadel thanks a lot for the info, will take a look at that
but before that devfile ready to be working, this odo-init-image still needed? 

do we have a forecast that start from when the odo-init-image is not needed anymore? thanks

**Comment by jichenjc** [comment]
@kadel can I know the plan of using devfiles? e.g openshift 4.4 , 4.5 etc?

**Comment by kadel** [comment]
> @kadel can I know the plan of using devfiles? e.g openshift 4.4 , 4.5 etc?

sorry for the late reply, I might already mention that somewhere else. odo is already using devfiles, you just need to enable the experimental mode `odo preference set experimental true`. Devfiles should "graduate" out of the experimental around OCP 4.5 timeframe, that is the current plan, it will depend on how fast we can stabilize it"

**Comment by sarveshtamba** [comment]
@kadel @jichenjc just saw this issue and related it to https://github.com/openshift/odo-init-image/issues/63
I need to build [odo-init-image](https://github.com/openshift/odo-init-image) for/on PowerPC64LE, so as to carry out [Deploying a devfile using odo](https://odo.dev/docs/deploying-a-devfile-using-odo/)
However as per above comments seems `odo-init-image` is going to be phased out gradually. Till then how does one carry out [Deploying a devfile using odo](https://odo.dev/docs/deploying-a-devfile-using-odo/) on ppc64le? Considering the issues I have mentioned in https://github.com/openshift/odo-init-image/issues/63

PS:- I already set `odo preference set experimental true` and was trying to use Devfiles until I realized I will need `odo-init-image` built for/on powerpc64le.

**Comment by jichenjc** [comment]
@sarveshtamba what we are doing is re-build the image on our own arch (s390x) and use the new image to do the test 
@zhengxm123 can you help to provide additional info here?

**Comment by sarveshtamba** [comment]
> @sarveshtamba what we are doing is re-build the image on our own arch (s390x) and use the new image to do the test
> @zhengxm123 can you help to provide additional info here?

@jichenjc I am trying to re-build the image on ppc64le power arch to use the new image to do the test, however facing the issues as mentioned in https://github.com/openshift/odo-init-image/issues/63
Any suggestions/inputs would be highly appreciated.
