### ISSUE TITLE
Latest images on 3.11 cluster reflects as unsupported

### ISSUE THREAD

**Issue by prietyc123** [openshift/odo-init-image#76]
Travis failure : https://travis-ci.com/github/openshift/odo-init-image/jobs/430956370#L1218-L1227 

nodejs latest says unsupported, however java throws `component type not found` https://travis-ci.com/github/openshift/odo-init-image/jobs/430956370#L1131

**Observation**: 

I am observing this failure since 1.1.5 odo-init release and there was a single pr https://github.com/openshift/odo-init-image/pull/70 change difference in 1.1.4 and 1.1.5 . I am not sure if `assemble-restrart` script could be responsible for this weird behaviour but that could be the initial research focus area. Again other than the assumption we need to analyse image details on 3.11 cluster for better understanding.

Note: This is only happening on odo-init-image repo.

**Comment by kadel** [comment]
Closing this in favor of https://github.com/openshift/odo/issues/4220

**Comment by prietyc123** [comment]
I think this issue belongs to odo-init-image repo. So we should not close the original issue. For more details refer comment https://github.com/openshift/odo/issues/4220#issuecomment-743142984
